[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
src = ["."]
# Enable Ruff formatter compatibility with Black-like rules
lint.select = [
  "E", "F", "I", # pycodestyle, pyflakes, isort
  "UP",            # pyupgrade
  "B",             # flake8-bugbear
  "SIM",           # flake8-simplify
  "PGH",           # pygrep-hooks
  "PL",            # pylint rules (subset)
  "RUF"
]
lint.ignore = [
  "E203",  # Whitespace before ':' (Black compatibility)
  "E266"   # Too many leading '#' for block comment
]
lint.unfixable = [
  "F401"  # Do not auto-delete unused imports blindly
]

[tool.ruff.lint.isort]
known-first-party = []
combine-as-imports = true
force-wrap-aliases = true
profile = "black"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.isort]
profile = "black"
line_length = 100

[tool.pyright]
typeCheckingMode = "basic"